language: node_js
cache: 
  directories:
    - node_module
    - ~/.npm
noed_js:
  - '12'
git: 
  depth: 3
script:
  - yarn build  
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy al proyecto"
  on: 
    branch: master